### ISSUE TITLE
Fix team abbreviation in Name Column to be the team they were on in that year, not their current year team.

### ISSUE THREAD

**Issue by CPLANT14** [mistakia/league#204]

**Comment by mistakia** [comment]
I think the team on year row will work better in its own column. We can either remove the team from the name column or leave it as the current team.

**Comment by CPLANT14** [comment]
> I think the team for the given year will work better in its own column. We can either remove the team from the name column or leave it as the current team.

I think the best course of action is to just remove the team from the name column, treat it like the position column is now.

**Comment by mistakia** [comment]
closing in favor of https://github.com/mistakia/league/issues/184
