### ISSUE TITLE
Request: Documentation (README)

### ISSUE THREAD

**Issue by philip** [mistakia/league#3]
This is a feature request for basic documentation (a README) to configure and run this for our own leagues :)

**Comment by mistakia** [comment]
Will do - only hurdle I for-see for self-hosted sites is some of the underlying data is from a paid service ([armchairanalysis.com](https://www.armchairanalysis.com/)), which a lot of features are derived from. I can partly address the issue by using [publicly available play-by-play data](https://github.com/CroppedClamp/nfl_pbps) but there's a good bit of _"charted"_ data that's mostly only available from paid sources. 

I plan to support self-hosted leagues as best as I can, at the same time, I'm happy to host as many leagues as I can afford.
